# Generated by Django 4.2.2 on 2023-06-17 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('valor_emprestico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Em Análise', max_length=30)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'proposta',
            },
        ),
    ]
