# Generated by Django 4.2.2 on 2023-06-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0002_alter_proposta_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='valor_emprestico',
            new_name='valor_emprestimo',
        ),
    ]
